# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

boxes = [
    {
        :name => "ansible-node1",
        :mem => "1024",
        :cpu => 1
    },
    {
        :name => "ansible-node2",
        :mem => "1024",
        :cpu => 1
    },
    {
        :name => "ansible-node3",
        :mem => "1024",
        :cpu => 1
    },
]

Vagrant.configure(2) do |config|

  config.vm.box = "generic/ubuntu2004"
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = opts[:mem]
        v.vmx["numvcpus"] = opts[:cpu]
      end
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end
      config.vm.provider "hyperv" do |v|
        v.cpus = opts[:cpu]
        v.maxmemory = opts[:mem]
        v.memory = opts[:mem]
      end
    end
  end
  config.vm.provision "shell", privileged: false, path: "./setup.sh"
end
